### ISSUE TITLE
The Evaluation Time of AVS-Semantic Datasets

### ISSUE THREAD

**Issue by SitongGong** [yannqi/COMBO-AVS#3]
Thanks for your wonderful job!
I'm facing a question while performing the training process of the AVS-Semantic Datasets. The evaluation time of this dataset is too long especially the computing process of miou metrics. The evaluation time can be over 6 hours for the whole dataset. Have you meet the similar questions and how to solve it?

**Comment by yannqi** [comment]
It is normal when I re-run the code of AVSS training. Could you provide more information about it?

Here is my evaluation logs(Only evaluation):
![issue_github](https://github.com/yannqi/COMBO-AVS/assets/51905299/c0c0a8a8-5c50-47c6-950c-2351073d0712)
![issue2](https://github.com/yannqi/COMBO-AVS/assets/51905299/b9ce3874-17c1-403c-b741-37b68676488a)
