### ISSUE TITLE
余弦相似度损失函数的问题

### ISSUE THREAD

**Issue by muuda** [yannqi/COMBO-AVS#4]
您好，非常感谢您的开源😊😊😊🥰🥰🥰。

我有一个余弦相似度损失函数的问题。
https://github.com/yannqi/COMBO-AVS/blob/7bf0e520a3df5bde4166ece895798c63a8b565ef/models/modeling/criterion.py#L216C1-L221C61
```             if cosine_weight == None:
                temp_cosine_loss = self.cosine_loss(
                    middle_attn_mask[:, frame, :].squeeze(dim=1), middle_attn_mask[:, frame + 1, :].squeeze(dim=1), torch.ones(bs).cuda()
                ) 
                exp_weight = torch.exp(-temp_cosine_loss)
                cosine_loss += temp_cosine_loss * exp_weight
```
您的上面这段代码，`cosine_loss `可以表示为 $s\times e^{-s}$,  但是您论文里给的是   $(1-s)\times e^{-s}$，其中$s$是计算出来的余弦相似度。   跟论文中的公式冲突了。感觉改为` cosine_loss += (1-temp_cosine_loss) * exp_weight`才对。

不知道是不是我理解错了，还请您指教一下。

**Comment by yannqi** [comment]
您好！您的关注非常细致👍🏻，原有Arxiv论文中此处存在公式笔误，请参考我们的代码的相似损失函数！我们已在论文中更正此处错误，并将在后续的Arxiv v2版本以及Camera-Ready版本中发布。

**Comment by muuda** [comment]
谢谢您的回答。 我还有一个疑惑(・∀・(・∀・(・∀・*)“

按着代码来的话，**相似损失函数**为 $s\times e^{-s}$ ,  其中 $s$ 是相邻两帧的余弦相似度, 且取值范围为 [-1,1]。我画了一下它的函数图像，如下所示：
![Snipaste_2024-03-20_16-42-07](https://github.com/yannqi/COMBO-AVS/assets/84113464/12ed0533-0850-4d66-98bf-9b16e394213b)
其中，**纵轴**表示损失函数值，**横轴**代表相邻两帧之间的余弦相似度。

我们想要**最小化损失函数**，那么 **s  就会趋近于-1** ，如图中红箭头的方向。 可是 s=-1表示相邻两帧的差异变大，跟预期矛盾。我们的目标应该想要让**相邻两帧之间的差异变小**才对吧，即让 s 趋近于1。


不知道这个该怎么理解呢😳（想了好久也没想明白），感觉论文中的损失函数写的是正确的，那样的话模型就会让s趋近于1。
再次感谢您的解答！

**Comment by yannqi** [comment]
😂你这里理解错误了，需要仔细看我们的代码[criterion.py#L217](https://github.com/yannqi/COMBO-AVS/blob/main/models/modeling/criterion.py#L217)和Pytorch的文档[torch.nn.CosineEmbeddingLoss](https://pytorch.org/docs/stable/generated/torch.nn.CosineEmbeddingLoss.html),

我们的代码中对应的公式，应当表示为:
$e^{-(1-s)}(1-s)$ 即 $e^{(s-1)}(1-s)$，与arxiv中的损失有一个微小的差异。
我们的损失的可视化图应该如下图所示：
![image](https://github.com/yannqi/COMBO-AVS/assets/51905299/e87ea43d-22a5-4b31-ad84-0bda10ede0a7)

即，当两张图片比较相似时，我们让它们更相似；当它们非常不相似时，我们让它们的损失也变小，不需要那么相似。这样就符合我们最直观的想法了。

ps：github的issue有时候容易漏看，欢迎邮件yangqi2021@ia.ac.cn或者微信13281172217联系！

**Comment by muuda** [comment]
谢谢，我明白了😁👍
