### ISSUE TITLE
ValueError: Cannot match one checkpoint key to multiple keys in the model.

### ISSUE THREAD

**Issue by fanna-1h** [yannqi/COMBO-AVS#5]
你好，请教一下跑代码的时候有没有遇到模型不匹配的问题，这个问题该怎么解决，试了一些方法，没有解决掉。
![微信图片_20240410110322](https://github.com/yannqi/COMBO-AVS/assets/115390546/1855d9a3-0743-4f0e-8fe0-260d1f4f5661)

**Comment by yannqi** [comment]
请参考我们的READMD.md   [README.md L49](https://github.com/yannqi/COMBO-AVS/blob/main/README.md?plain=1#L49)  解决此问题。
