### ISSUE TITLE
Inquery about  F-score Calculations.

### ISSUE THREAD

**Issue by aflyingnoob** [yannqi/COMBO-AVS#7]
Hello, I would like to ask about the calculation of Fm, which takes the maximum within a batch. Does this cause the F-score to vary with different batch sizes? In AVseg, the batch size used is 2, while you are using 8.
![image](https://github.com/user-attachments/assets/98ef19ee-0873-4d4c-8af8-234a99733401)

**Comment by yannqi** [comment]
We make the same batch size during the test in [test config](https://github.com/yannqi/COMBO-AVS/blob/main/configs/avs_s4/Test-R50-AVSS4-SemanticSegmentation.yaml).

**Comment by aflyingnoob** [comment]
I'm a bit curious whether it would be better to set this metric to 'mean' instead,  'max' was chosen to maintain consistency with previous papers.

Metrics should be independent of the order of image inputs and batch size. What do you think? Thank you.

**Comment by yannqi** [comment]
You know, we chose the 'max' with the same evaluation code for fair comparison.

I recommend using the same metric code, otherwise you need to re-evaluate other methods, while some code is not open source.
