### ISSUE TITLE
Question about audio shape 

### ISSUE THREAD

**Issue by c1ircle** [yannqi/COMBO-AVS#8]
In the code of transformer_decoder.py," audio_features = audio_features.repeat(1, self.num_queries, 1).reshape(self.num_queries, -1, audio_features.shape[-1])  " Is it really correct to use the reshape operation instead of permute here?

**Comment by yannqi** [comment]
According to https://pytorch.org/docs/stable/generated/torch.permute.html and https://pytorch.org/docs/stable/generated/torch.reshape.html, 'permute' is better. 
When possible, the return of the 'reshape' will be a view of input that is equal to 'permute'.
