### ISSUE TITLE
The GPU memory size required for AVSS tasks

### ISSUE THREAD

**Issue by zhaosonghui** [yannqi/COMBO-AVS#9]
Congratulations!  This is an exciting work!
I have a question to ask: what is the required GPU memory size for training the AVSS task? I set "IMS_PER_BATCH: 1" in the AVSS task, but it still shows "out of memory." My device is a 4090 GPU with 24GB of memory.

**Comment by yannqi** [comment]
You can use the mix-precision for saving the memory. 
We train our model on a single A100 40G GPU.
